### ISSUE TITLE
Bug: custom model gives a weird output to the console

### ISSUE THREAD

**Issue by SychAndrii** [aamfahim/explainer.js#10]
Having obtained a model and a token which are supported by the `groq` website, I have used them in the application to test them. However, I got this weird output when analyzing one of the files inside of `examples` directory:
![image](https://github.com/user-attachments/assets/adeb0737-42c9-4df7-961f-fe6e29a2951e)

I have used the `llama-guard-3-8b` model from HuggingFace to generate the description. I have researched what this model does, and basically what it does is classify content into safe/unsafe category:
https://huggingface.co/meta-llama/Llama-Guard-3-8B

So it's not a bug in the program, it's a lack of restrictions in the README and in validation. 

My suggestion: README should specify what LLMs are available to analyze the code and application should provide validation logic to limit a number of LLMs available for usage.

**Comment by aamfahim** [comment]
I think if the user is defining a model aside from the default one they should know what that model does exactly.
But I do agree README.md didn't have sufficient information. So, I updated it.
