### ISSUE TITLE
Refactoring: Inaccurate README file

### ISSUE THREAD

**Issue by SychAndrii** [aamfahim/explainer.js#9]
README file contains a lot of inaccurate information. What I managed to find:

1. There is no explainer.js file, there is index.js though
2. I talked to the teammate, he mentioned that `groq` has support only  should specify a list of allowed models inside of `--model` flag. I tried to use `openai-4o`, and it did not work. README should mention models that are supported by `groq` or provide  a link to the place where I can obtain them.
3. I talked to the teammate, he mentioned that api tokens that he expects are as well generated by the `groq`, my open AI API key did not work. This should also be mentioned in the README.
4. I found the api url option to be very confusing and unintuitive, it should be explained more in the README.

**Comment by aamfahim** [comment]
I think If you are using your custom model and/or base url and/or external API keys. You should refer to the Groq documentation.

That being  I do think README.md was lacking in terms of information. So, I have updated the README.md and have included link to Groq Documentation right at the beginning.
